version: "3.8"
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm start
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
